experiment_name: unet_lc_experiment
downstream_task: building
model_name: core_unet_nano
augmentations: True
batch_size: 256
model_device: cuda
generator_device: cpu
num_workers: 24
early_stop: 15
epochs: 500
input_channels: 10
output_channels: 1
input_size: 128
lr: 0.0001
lr_scheduler: reduce_on_plateau
n_shot: 50
split_ratio: null
regions: null
vis_val: True
warmup: False
warmp_steps: 5
warmup_gamma: 10
pretrained_model_path:
freeze_pretrained: False
data_path_128_10m: /home/phimultigpu/phileo_NFS/phileo_data/downstream/downstream_dataset_patches_np/
data_path_224_10m: /home/phimultigpu/phileo_NFS/phileo_data/downstream/downstream_dataset_patches_np_224/
data_path_224_30m: /home/phimultigpu/phileo_NFS/phileo_data/downstream/downstream_dataset_patches_np_HLS/
output_path: /home/phimultigpu/experiments
data_parallel: False
device_ids: [0, 1, 2, 3]